### ISSUE TITLE
TPCL Renderer?

### ISSUE THREAD

**Issue by lordzoco** [dittodhole/dotnet-Svg.Contrib.Render#12]
Hi there,
I'm wondering if there are any plan to implement a renderer for TPCL (Toshiba Tec Printer Command Language) in a near future.

I've already deployed a project for ZPL successfully, and now I have to do the similar way for render SVG labels in TPCL scripts.

Thanks in advance

Best regards

**Comment by dittodhole** [comment]
Hi!

Thanks for your suggestion! <3

Unfortunately, I am afraid that I won't implement TPCL in the near future, as I do not own any device, which implements TPCL. Any implementation within this parameters would be a blind flight (I've found some documentation on TPCL [here](http://www.tscprinters.com/cms/upload/download_en/TSPL_TSPL2_Programming.pdf), though) - I hope you understand!

Anyway, if you are interested, you could provide a PR, which I would be happy to integrate.

Best
Andreas
