### ISSUE TITLE
ZPL to PNG

### ISSUE THREAD

**Issue by smokinguns** [dittodhole/dotnet-Svg.Contrib.Render#14]
I know this is way off, but is there not a library or way to convert zpl to png. I know of an online service, but am curious how they are able to do it.

**Comment by dittodhole** [comment]
I suggest to base your stack on _.svg_-files. This way you can render it to PNG (via `SvgDocument.Draw`, available with [Svg](https://www.nuget.org/packages/Svg/))  and to ZPL (via `RendererBase<TContainer>.GetTranslation`, available with this suite).

**Comment by smokinguns** [comment]
thanks for the response. I couldn't agree more. I'm stuck in a world that i receive zpl and need to convert to other formats.

**Comment by dittodhole** [comment]
In fact, one could simply reverse the conversion-logic, to create SVG out of ZPL ... but this is another story :)
